# Cada servicio debe tener un puerto único
server:
  port: 8083

# Nombre del servicio
spring:
  application:
    name: ms-solicitudes

# --- Configuración de la Base de Datos ÚNICA ---
  datasource:
    url: jdbc:postgresql://localhost:5432/db_logistica
    username: tpi_user         
    password: 12345678      
    driver-class-name: org.postgresql.Driver

  # --- Configuración de JPA (Hibernate) ---
  jpa:
    hibernate:
      # 'update' modifica la BD al arrancar (solo para desarrollo)
      ddl-auto: update
    properties:
      hibernate:
        # Eliminamos esta línea para usar el schema 'public' por defecto
        # default_schema: solicitudes

# --- Configuración de Seguridad (Keycloak) ---
# Las propiedades de 'issuer-uri' se configurarán en docker-compose

# --- Configuración de Eureka Client ---
eureka:
  client:
    # URL donde corre tu servidor Eureka (que configurarás después)
    service-url:
      defaultZone: http://localhost:8761/eureka/
    # CAMBIO: Confirmamos que está deshabilitado como pediste.
    enabled: false